# Generated by Django 5.0 on 2024-03-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_remove_train_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
