# Generated by Django 5.0 on 2024-03-28 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0004_train_fare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='train',
            name='to_city',
        ),
        migrations.AddField(
            model_name='train',
            name='from_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_city', to='railway.station'),
        ),
        migrations.AddField(
            model_name='train',
            name='to_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_city', to='railway.station'),
        ),
    ]
