# Generated by Django 5.0 on 2024-03-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0005_remove_train_from_city_remove_train_to_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date2',
        ),
    ]
