# Generated by Django 5.0 on 2024-03-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='train_image',
            field=models.ImageField(blank=True, null=True, upload_to='train_images/'),
        ),
    ]
